import { useEffect, useRef, useState } from "react";
import { api } from "./api";
import { courses } from "./data";
import "./styles.css";

const tokenKey = "cloudprep-token";
const initials = (name = "") => name.split(/\s+/).map(p => p[0]).slice(0, 2).join("").toUpperCase();
const duration = (seconds = 0) => `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`;

function Header({ user, onProfile, onLogout }) { return <header className="header"><button className="brand" onClick={user ? onProfile : undefined}><span className="brand-mark"><i/><i/><i/></span>Cloud<span>Prep</span></button>{user && <div className="header-user"><button className="avatar-button" onClick={onProfile}>{initials(user.name)}</button><button className="logout-link" onClick={onLogout}>Sign out</button></div>}</header>; }
function Auth({ onAuth }) {
  const [registering, setRegistering] = useState(false), [form, setForm] = useState({ name: "", email: "", password: "", confirm: "" }), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const submit = async event => { event.preventDefault(); setError(""); if (registering && form.password !== form.confirm) return setError("Passwords do not match."); setBusy(true); try { const result = await (registering ? api.register(form) : api.login(form)); localStorage.setItem(tokenKey, result.token); onAuth(result.user); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main className="auth-layout"><div className="auth-copy"><p className="eyebrow">Cloud certification practice</p><h1>Every question is a fresh challenge.</h1><p>Practise Docker, Kubernetes, DevOps, and Azure with shuffled questions and saved progress.</p></div><form className="auth-card" onSubmit={submit}><p className="eyebrow">{registering ? "Create account" : "Welcome back"}</p><h2>{registering ? "Start your profile" : "Sign in"}</h2>{registering && <label>Full name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} minLength="2" required /></label>}<label>Email address<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label><label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} minLength="6" required /></label>{registering && <label>Confirm password<input type="password" value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })} minLength="6" required /></label>}<p className="error">{error}</p><button className="button primary" disabled={busy}>{busy ? "Please wait…" : registering ? "Create account" : "Sign in"}</button><p className="switch">{registering ? "Already have an account?" : "New to CloudPrep?"} <button type="button" onClick={() => setRegistering(!registering)}>{registering ? "Sign in" : "Create an account"}</button></p></form></main>;
}
function Home({ onCourse }) { return <main className="shell"><section className="hero"><p className="eyebrow">Cloud certification practice</p><h1>Build confidence.<br/>Master the cloud.</h1><p>Timed, shuffled question banks with answer review and persistent progress.</p></section><div className="section-title"><div><p className="eyebrow">Course library</p><h2>Choose your certification</h2></div><span>{courses.length} available</span></div>{courses.map(course => <button className="course-card" key={course.code} onClick={() => onCourse(course.code)}><div className="course-icon">✦</div><div><span className="pill">Available</span><h3>{course.code}</h3><p>{course.title}</p><div className="card-meta"><span>5 sections</span><span>100 shuffled questions</span><b>Explore →</b></div></div></button>)}</main>; }
function Sections({ course, onBack, onStart }) { return <main className="shell"><button className="back" onClick={onBack}>← Back to courses</button><div className="section-hero"><div><p className="eyebrow">{course.code} · {course.title}</p><h1>Choose a section</h1><p>Each section gives you 20 questions. Questions are shuffled and never repeated during an attempt.</p></div><strong>5<small>sections</small></strong></div><div className="section-grid">{course.sections.map((section, index) => <button className="section-card" key={section.name} onClick={() => onStart(index)}><div className="section-number">0{index + 1}<span>20 questions</span></div><h2>{section.name}</h2><p>{section.description}</p><b>Start section →</b></button>)}</div></main>; }
function Quiz({ course, sectionIndex, onBack, onComplete }) {
  const section = course.sections[sectionIndex], [question, setQuestion] = useState(null), [selected, setSelected] = useState(null), [correct, setCorrect] = useState(0), [answers, setAnswers] = useState([]), [number, setNumber] = useState(1), [loading, setLoading] = useState(true), [error, setError] = useState(""), [elapsed, setElapsed] = useState(0), asked = useRef([]), started = useRef(Date.now());
  const load = async () => { setLoading(true); setError(""); setSelected(null); try { const result = await api.nextQuestion(course.code, section.name, asked.current); setQuestion(result.question); asked.current = [...asked.current, result.question.id]; } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [course.code, section.name]); useEffect(() => { const timer = setInterval(() => setElapsed(Math.floor((Date.now() - started.current) / 1000)), 1000); return () => clearInterval(timer); }, []);
  const next = async () => { if (selected === null) return; const nextCorrect = correct + (selected === question.answer ? 1 : 0), nextAnswers = [...answers, { question: question.question, options: question.options, selected, correct: question.answer, explanation: question.explanation }]; if (number === 20) { setLoading(true); try { const durationSeconds = Math.max(1, Math.floor((Date.now() - started.current) / 1000)), result = await api.saveAttempt({ course: course.code, section: section.name, correct: nextCorrect, total: 20, durationSeconds }); onComplete({ user: result.user, review: { course: course.code, section: section.name, correct: nextCorrect, total: 20, durationSeconds, answers: nextAnswers } }); } catch (e) { setError(e.message); } finally { setLoading(false); } return; } setAnswers(nextAnswers); setCorrect(nextCorrect); setNumber(number + 1); await load(); };
  return <main className="shell quiz"><button className="back" onClick={onBack}>← Back to sections</button><div className="quiz-heading"><div><p className="eyebrow">{course.code} · {section.name}</p><h1>Question {number} of 20</h1></div><span className="quiz-time">⏱ {duration(elapsed)} · {Math.round(((number - 1) / 20) * 100)}%</span></div><div className="progress"><i style={{ width: `${number / 20 * 100}%` }}/></div>{loading ? <div className="question-card loading"><div className="spinner"/><h2>Shuffling a fresh question…</h2></div> : error ? <div className="question-card error-card"><h2>Question unavailable</h2><p>{error}</p><button className="button primary" onClick={load}>Try again</button></div> : <div className="question-card"><p className="eyebrow">Fresh question</p><h2>{question.question}</h2><div className="options">{question.options.map((option, index) => <button key={option} className={`option ${selected === index ? "selected" : ""}`} onClick={() => setSelected(index)}><span>{String.fromCharCode(65 + index)}</span>{option}</button>)}</div><div className="question-actions"><span>{selected === null ? "Choose one answer" : "Answer selected"}</span><button className="button primary" disabled={selected === null} onClick={next}>{number === 20 ? "Finish section" : "Next question →"}</button></div></div>}</main>;
}
function Results({ review, onSections, onProfile }) { const percentage = Math.round(review.correct / review.total * 100); return <main className="shell results"><div className="result-banner"><div><p className="eyebrow">{review.course} · Assessment complete</p><h1>{percentage >= 70 ? "Strong work — you passed." : "Good start — keep building."}</h1><p>{review.correct} of {review.total} answers correct in {review.section}.</p></div><div className="result-score"><strong>{percentage}%</strong><span>⏱ {duration(review.durationSeconds)}</span></div></div><div className="result-actions"><button className="button primary" onClick={onSections}>Try another section</button><button className="button secondary" onClick={onProfile}>Open profile</button></div><div className="section-title"><div><p className="eyebrow">Answer review</p><h2>Review your answers</h2></div></div><div className="review-list">{review.answers.map((answer, index) => { const ok = answer.selected === answer.correct; return <article className={`review-card ${ok ? "review-correct" : "review-wrong"}`} key={`${index}-${answer.question}`}><div className="review-label">{ok ? "✓ Correct" : "✕ Incorrect"}<span>Question {index + 1}</span></div><h3>{answer.question}</h3><p className={ok ? "answer good" : "answer bad"}><b>Your answer:</b> {answer.options[answer.selected]}</p>{!ok && <p className="answer good"><b>Correct answer:</b> {answer.options[answer.correct]}</p>}<p className="explanation"><b>Why:</b> {answer.explanation}</p></article>; })}</div></main>; }
function Profile({ user, onBack, onLogout }) { const attempts = user.attempts || [], totalCorrect = attempts.reduce((s, a) => s + a.correct, 0), totalQuestions = attempts.reduce((s, a) => s + a.total, 0); return <main className="shell"><button className="back" onClick={onBack}>← Back to courses</button><section className="profile-banner"><div className="large-avatar">{initials(user.name)}</div><div><p className="eyebrow">Your profile</p><h1>{user.name}</h1><p>{user.email}</p></div><button className="button ghost" onClick={onLogout}>Sign out</button></section><div className="stats"><article><span>Total attempts</span><strong>{attempts.length}</strong></article><article><span>Passed attempts</span><strong>{attempts.filter(a => a.passed).length}</strong></article><article><span>Total score</span><strong>{totalCorrect}<small> / {totalQuestions}</small></strong></article></div><div className="section-title"><div><p className="eyebrow">Learning activity</p><h2>Past attempts</h2></div></div><div className="attempts">{attempts.map(a => <article key={a._id}><div><h3>{a.course || "AZ-104"} · {a.section}</h3><p>{new Date(a.completedAt).toLocaleString()}</p></div><span className={a.passed ? "passed" : "review"}>{a.passed ? "Passed" : "Review"}</span><strong>{a.percentage}%<small>{a.correct} / {a.total} · {duration(a.durationSeconds)}</small></strong></article>)}</div></main>; }
export default function App() { const [user, setUser] = useState(null), [page, setPage] = useState("home"), [courseCode, setCourseCode] = useState("AZ-104"), [sectionIndex, setSectionIndex] = useState(null), [review, setReview] = useState(null), [checking, setChecking] = useState(true), course = courses.find(c => c.code === courseCode) || courses[0]; useEffect(() => { if (!localStorage.getItem(tokenKey)) return setChecking(false); api.me().then(r => setUser(r.user)).catch(() => localStorage.removeItem(tokenKey)).finally(() => setChecking(false)); }, []); const logout = () => { localStorage.removeItem(tokenKey); setUser(null); setPage("home"); }; const openProfile = async () => { try { const r = await api.me(); setUser(r.user); setPage("profile"); } catch { logout(); } }; if (checking) return <><Header/><div className="center-loader">Loading CloudPrep…</div></>; return <><Header user={user} onProfile={openProfile} onLogout={logout}/>{!user ? <Auth onAuth={u => { setUser(u); setPage("home"); }}/> : page === "home" ? <Home onCourse={code => { setCourseCode(code); setPage("sections"); }}/> : page === "sections" ? <Sections course={course} onBack={() => setPage("home")} onStart={i => { setSectionIndex(i); setPage("quiz"); }}/> : page === "quiz" ? <Quiz key={`${courseCode}-${sectionIndex}`} course={course} sectionIndex={sectionIndex} onBack={() => setPage("sections")} onComplete={r => { setUser(r.user); setReview(r.review); setPage("results"); }}/> : page === "results" ? <Results review={review} onSections={() => setPage("sections")} onProfile={openProfile}/> : <Profile user={user} onBack={() => setPage("home")} onLogout={logout}/>}</>; }
